package lab3;

enum TokenType {
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_PARENTHESES, RIGHT_PARENTHESES,
    LEFT_CURLY_BRACKET, RIGHT_CURLY_BRACKET,
    COMMA, SEMICOLON, COLON,
    PLUS, MINUS, SLASH, STAR,


    NOT, EQUAL, NOT_EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    IDENTIFIER,
    INT, STRING, FLOAT,
    VOID, RETURN, IF, ELSE,

    EOF
}